# Generated by Django 2.2 on 2019-04-23 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igallery', '0002_auto_20190419_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
